/*----------------------------------------------------------
MASV: 1412274, 1412282, 1412414
HO TEN CAC THANH VIEN NHOM: 
	1412274 - Nguyen Hoang Kim 
	1412282 - Nguyen Hoang Lan 
	1412414 - Vuong Thien Phu
LAB: 04 - NHOM
NGAY: 13/6/2018
----------------------------------------------------------*/
USE QLSVNhom
GO

---------------------------------Bảng SINHVIEN---------------------------------
--Thêm sinh viên
CREATE PROCEDURE SP_INS_SINHVIEN @MASV VARCHAR(20), 
								 @HOTEN NVARCHAR(100), 
								 @NGAYSINH DATETIME, 
								 @DIACHI NVARCHAR(200), 
								 @MALOP VARCHAR(20), 
								 @TENDN NVARCHAR(100), 
								 @MATKHAU VARCHAR(2048)
AS
BEGIN
	INSERT INTO SINHVIEN VALUES(@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, CONVERT(VARBINARY(2048), @MATKHAU))
END
GO

DROP PROCEDURE SP_INS_SINHVIEN
GO

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN HOANG KIM', '1/1/1990', '280 AN DUONG VUONG', '14CTT2', 'nhkim', '123456' --0xE10ADC3949BA59ABBE56E057F20F883E
EXEC SP_INS_SINHVIEN 'SV02', 'PHAN KHANH LAM', '1/1/1990', '450 AU CO', '14CTT2', 'pklam', '123456'
GO

SELECT * FROM SINHVIEN
GO

DELETE FROM SINHVIEN
GO

--Load danh sách sinh viên
CREATE PROCEDURE SP_DSSV @MALOP VARCHAR(20)
AS
BEGIN
	SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, CONVERT(VARCHAR(2048), MATKHAU) AS MATKHAU 
	FROM SINHVIEN
	WHERE MALOP = @MALOP
END
GO

EXEC SP_DSSV ''
GO

DROP PROCEDURE SP_DSSV
GO

--Cập nhật sinh viên
CREATE PROCEDURE SP_UPDATE_SV @MASV VARCHAR(20), 
							  @HOTEN NVARCHAR(100),
							  @NGAYSINH DATETIME,
							  @DIACHI NVARCHAR(200),
							  @TENDN NVARCHAR(100),
							  @MATKHAU VARCHAR(2048)
AS
BEGIN
	DECLARE @MATKHAU_MAHOA VARBINARY(2048), @MATKHAU_TEMP VARBINARY(2048)
	IF (@HOTEN = '')
		SELECT @HOTEN = HOTEN FROM SINHVIEN WHERE MASV = @MASV
	IF (@NGAYSINH = '')
		SELECT @NGAYSINH = NGAYSINH FROM SINHVIEN WHERE MASV = @MASV
	IF (@DIACHI = '')
		SELECT @DIACHI = DIACHI FROM SINHVIEN WHERE MASV = @MASV
	IF (@TENDN = '')
		SELECT @TENDN = TENDN FROM SINHVIEN WHERE MASV = @MASV
	
	IF (@MATKHAU = '')
		SELECT @MATKHAU_MAHOA = MATKHAU FROM SINHVIEN WHERE MASV = @MASV
	IF (@MATKHAU != '')
		SELECT @MATKHAU_MAHOA = CONVERT(VARBINARY(2048), @MATKHAU)

	UPDATE SINHVIEN SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH, DIACHI = @DIACHI, TENDN = @TENDN, MATKHAU = @MATKHAU_MAHOA
	WHERE MASV = @MASV

END
GO

DROP PROCEDURE SP_UPDATE_SV
GO

--Lấy mật khẩu trước đó ở dạng VARCHAR
CREATE PROCEDURE SP_GET_MK @MASV VARCHAR(20), @MATKHAU VARCHAR(2048) OUT
AS
BEGIN
	SELECT @MATKHAU = CONVERT(VARCHAR(2048), MATKHAU) FROM SINHVIEN WHERE MASV = @MASV
END
GO

DROP PROCEDURE SP_GET_MK
GO

--Xóa sinh viên
CREATE PROCEDURE SP_DELETE_SV @MASV VARCHAR(20)
AS
BEGIN
	--DELETE FROM BANGDIEM WHERE MASV = @MASV
	DELETE FROM SINHVIEN WHERE MASV = @MASV
END
GO

DROP PROCEDURE SP_DELETE_SV
GO

--Lấy mã SV lớn nhất
CREATE PROCEDURE SP_MAX_MASV @MASV VARCHAR(20) OUT
AS
BEGIN
	SELECT @MASV = MAX(MASV)
	FROM SINHVIEN
END
GO

DROP PROCEDURE SP_MAX_MASV
GO
-------------------------------------------------------------------------------