/*----------------------------------------------------------
MASV: 1412274, 1412282, 1412414
HO TEN CAC THANH VIEN NHOM: 1412274 - Nguyen Hoang Kim, 1412282 - Nguyen Hoang Lan, 1412414 - Vuong Thien Phu
LAB: 04 - NHOM
NGAY: 13/6/2018
----------------------------------------------------------*/
--CAU LENH TAO DB
CREATE DATABASE QLSVNhom
GO

USE QLSVNhom
GO

alter database QLSVN
set compatibility_level = 120

--CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN
(
	MASV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL, 
	MATKHAU VARBINARY(2048) NOT NULL
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(2048),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(2048) NOT NULL,
	PUBKEY VARCHAR(20)
)
GO

CREATE TABLE LOP
(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)		
)
GO

CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20) PRIMARY KEY,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
)
GO

CREATE TABLE BANGDIEM
(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(2048),
	PRIMARY KEY(MASV, MAHP)
)
GO

--CAC CAU LENH TAO KHOA NGOAI
/*ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
GO
*/
--CAC LENH TAO STORE PROCEDURE
--i.Stored dùng để thêm mới dữ liệu (Insert) vào table SINHVIEN, trong đó
--• Thuộc tính MATKHAU được mã hóa (HASH) sử dụng SHA1
--• Thuộc tính LUONG sẽ được mã hóa từ tham số LUONGCB sử dụng thuật toán RSA
--512, với khóa bí mật là tham số MK được truyền vào.
--• Thuộc tính PUBKEY sẽ lưu trữ tên khóa công khai được tạo ra ứng với nhân viên
--này, giá trị này sẽ lưu thông tin khóa công khai được tạo từ client.
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN @MANV VARCHAR(20), @HOTEN NVARCHAR(100), @EMAIL VARCHAR(20),
@LUONG VARCHAR(1024), @TENDN NVARCHAR(100), @MATKHAU VARCHAR(1024)
AS 
BEGIN
DECLARE @LUONG_HASH VARBINARY(2048)
SET @LUONG_HASH = CONVERT(VARBINARY, @LUONG)
DECLARE @MATKHAU_HASH VARBINARY(2048)
SET @MATKHAU_HASH = CONVERT(VARBINARY, @MATKHAU)

INSERT INTO NHANVIEN VALUES (@MANV, @HOTEN, @EMAIL, @LUONG_HASH, @TENDN, @MATKHAU_HASH, @MANV)
END
go
--ii. Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)
CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN @MANV VARCHAR(20), @MATKHAU VARCHAR(1024)
AS
BEGIN
DECLARE @MATKHAU_BINARY VARBINARY(2048)
SET @MATKHAU_BINARY = CONVERT(VARBINARY, @MATKHAU)

SELECT MANV, HOTEN, EMAIL, LUONG FROM NHANVIEN WHERE MANV = @MANV AND MATKHAU = @MATKHAU_BINARY

END

